-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF SECURITY DEFINER
AS $BODY$
begin
  insert into public.users (id, email)
  values (new.id, new.email);
  return new;
end;
$BODY$;

ALTER FUNCTION public.handle_new_user()
    OWNER TO supabase_admin;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO postgres;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO supabase_admin;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;

GRANT EXECUTE ON FUNCTION public.handle_new_user() TO PUBLIC;

CREATE TABLE IF NOT EXISTS public.posts_claimed
(
    "userId" uuid NOT NULL,
    "postId" uuid NOT NULL,
    CONSTRAINT posts_claimed_pkey PRIMARY KEY ("userId", "postId"),
    CONSTRAINT "posts_claimed_postId_fkey" FOREIGN KEY ("postId")
        REFERENCES public.posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "posts_claimed_userId_fkey" FOREIGN KEY ("userId")
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.posts_claimed
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.posts_claimed TO anon;

GRANT ALL ON TABLE public.posts_claimed TO postgres;

GRANT ALL ON TABLE public.posts_claimed TO supabase_admin;

GRANT ALL ON TABLE public.posts_claimed TO authenticated;

GRANT ALL ON TABLE public.posts_claimed TO service_role;

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    email text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_id_fkey FOREIGN KEY (id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.users TO anon;

GRANT ALL ON TABLE public.users TO postgres;

GRANT ALL ON TABLE public.users TO supabase_admin;

GRANT ALL ON TABLE public.users TO authenticated;

GRANT ALL ON TABLE public.users TO service_role;

CREATE TABLE IF NOT EXISTS public.wishlist_post
(
    "wishlistId" uuid NOT NULL,
    "postId" uuid,
    CONSTRAINT wishlist_post_pkey PRIMARY KEY ("wishlistId"),
    CONSTRAINT "wishlist_post_postId_fkey" FOREIGN KEY ("postId")
        REFERENCES public.posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "wishlist_post_wishlistId_fkey" FOREIGN KEY ("wishlistId")
        REFERENCES public.wishlists (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.wishlist_post
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.wishlist_post TO anon;

GRANT ALL ON TABLE public.wishlist_post TO postgres;

GRANT ALL ON TABLE public.wishlist_post TO supabase_admin;

GRANT ALL ON TABLE public.wishlist_post TO authenticated;

GRANT ALL ON TABLE public.wishlist_post TO service_role;

CREATE TABLE IF NOT EXISTS public.user_post
(
    "userId" uuid NOT NULL,
    "postId" uuid NOT NULL,
    CONSTRAINT user_post_pkey PRIMARY KEY ("userId", "postId"),
    CONSTRAINT "user_post_postId_fkey" FOREIGN KEY ("postId")
        REFERENCES public.posts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "user_post_userId_fkey" FOREIGN KEY ("userId")
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_post
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.user_post TO anon;

GRANT ALL ON TABLE public.user_post TO postgres;

GRANT ALL ON TABLE public.user_post TO supabase_admin;

GRANT ALL ON TABLE public.user_post TO authenticated;

GRANT ALL ON TABLE public.user_post TO service_role;

CREATE TABLE IF NOT EXISTS public.posts
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default",
    created_by uuid,
    price text COLLATE pg_catalog."default",
    url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT posts_pkey PRIMARY KEY (id),
    CONSTRAINT posts_created_by_fkey FOREIGN KEY (created_by)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.posts
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.posts TO anon;

GRANT ALL ON TABLE public.posts TO postgres;

GRANT ALL ON TABLE public.posts TO supabase_admin;

GRANT ALL ON TABLE public.posts TO authenticated;

GRANT ALL ON TABLE public.posts TO service_role;

CREATE TABLE IF NOT EXISTS public.wishlists
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone DEFAULT now(),
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT wishlists_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.wishlists
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.wishlists TO anon;

GRANT ALL ON TABLE public.wishlists TO postgres;

GRANT ALL ON TABLE public.wishlists TO supabase_admin;

GRANT ALL ON TABLE public.wishlists TO authenticated;

GRANT ALL ON TABLE public.wishlists TO service_role;

CREATE TABLE IF NOT EXISTS public.user_wishlist
(
    "userId" uuid NOT NULL,
    "wishlistId" uuid NOT NULL,
    CONSTRAINT user_wishlist_pkey PRIMARY KEY ("userId", "wishlistId"),
    CONSTRAINT "user_wishlist_userId_fkey" FOREIGN KEY ("userId")
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "user_wishlist_wishlistId_fkey" FOREIGN KEY ("wishlistId")
        REFERENCES public.wishlists (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_wishlist
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.user_wishlist TO anon;

GRANT ALL ON TABLE public.user_wishlist TO postgres;

GRANT ALL ON TABLE public.user_wishlist TO supabase_admin;

GRANT ALL ON TABLE public.user_wishlist TO authenticated;

GRANT ALL ON TABLE public.user_wishlist TO service_role;

REVOKE ALL ON TABLE public.employees FROM authenticated;
REVOKE ALL ON TABLE public.employees FROM postgres;
REVOKE ALL ON TABLE public.employees FROM service_role;
GRANT ALL ON TABLE public.employees TO authenticated;

GRANT ALL ON TABLE public.employees TO postgres;

GRANT ALL ON TABLE public.employees TO service_role;
